baseurl: https://vahanaslanyan.com
publishdir: docs
DefaultContentLanguage: en
title: Vahan Aslanyan
relativeurls: true
theme: "beautifulhugo"
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  homeTitle: Vahan Aslanyan
  comments: no
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/plots.png
  logo: img/IMG-4344.jpg
  mainSections:
  - post
  readingTime: no
  rss: no
  showRelatedPosts: no
  socialShare: no
  subtitle: Biostatistics PhD student at USC
  useHLJS: yes
  wordCount: no
permalinks:
  post: /:year/:month/:day/:slug/
Author:
  github: vahanaslanyan
  linkedin: vahan-aslanyan
  name: Vahan Aslanyan
  twitter: VahanAslanyan
menu:
  main:
    - name: Resume
      url: resume/VahanAslanyan_Resume_Oct2024.pdf
      weight: 4
    - name: Blog
      url: ""
      weight: 1
    - name: About
      url: page/about
      weight: 2
    - identifier: Research
      name: Research
      weight: 3
    - name: Google Scholar
      parent: Research
      url: https://scholar.google.com/citations?user=1R7h3P4AAAAJ&hl=en
      weight: 1
    - name: Posters
      parent: Research
      url: https://drive.google.com/drive/folders/1g6oSiv8pQOIVaTZFNH2DNOa74N46JgT8
      weight: 2
    - name: Talks
      parent: Research
      url: talk/talks
      weight: 3
      
